services:
  phoscon:
    image: marthoc/deconz
    container_name: deconz
    restart: always
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2698184-if00
      # to find the device path, run the following command on the host: ls /dev/serial/by-id/
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2698184-if00:/dev/ttyUSB0
    ports:
      - 8080:8080
      - 8443:8443
    network_mode: host # Required for access to Zigbee stick
    privileged: true # Allows access to USB device

  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: always
    environment:
      - TZ=Europe/Berlin # Change to your timezone
    volumes:
      - /applehome/homebridge/config:/homebridge/config
      - /applehome/homebridge/persist:/homebridge/persist
      - /applehome/homebridge/storage:/homebridge/storage
    ports:
      - 8581:8581
      - 51826:51826
    depends_on:
      - phoscon
    network_mode: host # Use host networking so Homebridge can find the ConBee stick
